StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{663E7383053A8001}" {
   Id "armst_quest_action_info"
   Target_en_us "Tell about yourself"
   Target_ru_ru "Расскажи о себе"
   Modified 1715372208
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663CE74BDDC15010}" {
   Id "armst_quest_aerodrom_item"
   Target_en_us "Radio parts"
   Target_ru_ru "Радиозапчасти"
   Modified 1715270027
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663CE74A6668545F}" {
   Id "armst_quest_aerodrom_quest_action"
   Target_en_us "Search for spare parts at Aerodrom"
   Target_ru_ru "Поиск запчастей на Аэродроме"
   Modified 1715269805
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663CE74A10E82AF6}" {
   Id "armst_quest_aerodrom_quest_finish"
   Target_en_us "Thank you for completing our mission. We received the radio equipment you found at the Military Airfield. It will be very useful to us."\
   ""\
   "We paid you the promised reward. You can check your account."\
   ""\
   "If you have any questions or want to participate in our other operations, feel free to contact me. We are always looking for reliable and qualified stalkers."
   Target_ru_ru "Спасибо, что выполнил наше задание. Мы получили радио-аппаратуру, которую ты нашел на Военном Аэродроме. Она будет очень полезна для нас."\
   ""\
   "Мы заплатили тебе обещанное вознаграждение. Ты можешь проверить свой счет. "\
   ""\
   "Если у тебя будут какие-либо вопросы или ты захочешь принять участие в других наших операциях, не стесняйся связаться со мной. Мы всегда ищем надежных и квалифицированных сталкеров."
   Modified 1715269904
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663CE74ABE0760E6}" {
   Id "armst_quest_aerodrom_quest_start"
   Target_en_us "Hello, stalker. My name is Victor, I am from the Smugglers group. I have a task for you. We need radio equipment from the Military Airfield. There are several helicopters left there that were not completely looted. We need you to search them and find the necessary equipment."\
   ""\
   "You must be careful, the Airfield is not the safest place. There may be bandits, mutants and other dangers. But we will pay well if you cope with the task."\
   ""\
   "You will find several helicopters at the Airfield. Search them and find radio equipment. We need any working equipment that you can find. When you find what we need, bring it to our base."\
   ""\
   "Be careful and good luck to you."
   Target_ru_ru "Здравствуй, сталкер. Меня зовут Виктор, я из группировки Контрабандистов. У меня есть задание для тебя. Нам нужна радио-аппаратура с Военного Аэродрома. Там осталось несколько вертолетов, которые не были полностью разграблены. Нам нужно, чтобы ты обыскал их и нашел нужную аппаратуру."\
   ""\
   "Ты должен быть осторожен, Аэродром не самое безопасное место. Там могут быть бандиты, мутанты и другие опасности. Но мы хорошо заплатим, если ты справишься с заданием."\
   ""\
   "Ты найдешь несколько вертолетов на Аэродроме. Обыщи их и найди радио-аппаратуру. Нам нужна любая рабочая аппаратура, которую ты сможешь найти. Когда ты найдешь то, что нам нужно, тащи к нам на базу."\
   ""\
   "Будь осторожен и удачи тебе."
   Modified 1715269773
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663E738C91014E3A}" {
   Id "armst_quest_bar_kb_info"
   Target_en_us "My name is Sam, I am the bartender here at our base. We are the Smugglers, and this is our lair. We are not the biggest group, but we know how to survive in the Zone."\
   ""\
   "I have been working here for a long time, and I have seen many stalkers coming and going. Some of them return with rich loot, others... not so much. But we are always ready to help those who need help."\
   ""\
   "Our base is a place where you can relax, drink and eat. We do not ask many questions, you just pay for what you need, and that's it. We have everything a stalker needs: food, water, ammo, equipment... and, of course, booze."\
   ""\
   "As you agreed with your guide, your money is in the suitcase on the left."
   Target_ru_ru "Меня зовут Сэм, я бармен здесь, на нашей базе. Мы - Контрабандисты, и это наше логово. Мы не самая большая группировка, но мы знаем, как выжить в Зоне."\
   ""\
   "Я уже давно работаю здесь, и я видел много сталкеров, приходящих и уходящих. Некоторые из них возвращаются с богатой добычей, другие... не очень. Но мы всегда готовы помочь тем, кто нуждается в помощи."\
   ""\
   "Наша база - это место, где можно отдохнуть, выпить и поесть. Мы не задаем много вопросов, просто платишь за то, что тебе нужно, и все. У нас есть все, что нужно сталкеру: еда, вода, патроны, снаряжение... и, конечно, выпивка."\
   ""\
   "Как ты и договаривался со своим проводником, твои деньги лежат в чемодане слева. "
   Modified 1715373685
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71BFC1493767}" {
   Id "armst_quest_forest_science_item"
   Target_en_us "Notebook of the Lost Expedition Forest"
   Target_ru_ru "Блокнот пропавшей экспедиции Лес"
   Modified 1715246999
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71B977E4A76F}" {
   Id "armst_quest_forest_search_ural"
   Target_en_us "Search group \"Prometheus\""
   Target_ru_ru "Поиск группы \"Прометей\""
   Modified 1715373860
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71B864779F34}" {
   Id "armst_quest_forest_search_ural_finish_mission"
   Target_en_us "Thank you for finding our data. We have received it. Unfortunately, our expedition did not return. We suffered heavy losses. The data you found will be very useful to us. It will help us better understand the anomalies in the Zone."\
   ""\
   "I must admit that we were too optimistic when sending an expedition to the Forest. We knew it was risky, but we did not expect it to end so tragically. Thank you for honoring the memory of our colleagues and returning their work to us."\
   ""\
   "If you have the opportunity, we will be glad if you continue to help us in our research. We need people willing to take risks for the sake of science."
   Target_ru_ru "Спасибо, что нашли наши данные. Мы получили их. К сожалению, наша экспедиция не вернулась. Мы понесли тяжелые потери. Данные, которые вы нашли, будут очень полезны для нас. Они помогут нам лучше понять аномалии в Зоне."\
   ""\
   "Я должен признать, что мы были слишком оптимистичны, отправляя экспедицию в Лес. Мы знали, что это рискованно, но мы не ожидали, что все закончится так трагически. Спасибо, что почтили память наших коллег и вернули нам их работу."\
   ""\
   "Если у вас будет возможность, мы будем рады, если вы продолжите помогать нам в наших исследованиях. Мы нуждаемся в людях, готовых рисковать ради науки."
   Modified 1715246874
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71BF9E35D7C2}" {
   Id "armst_quest_forest_search_ural_stage_1"
   Target_en_us "Upon inspection of the helicopter, you discovered crew records indicating that the bunker was dropped near the Radar Station."
   Target_ru_ru "При осмотре вертолета вы обнаружили записи экипажа, в которых указано, что бункер был сброшен недалеко от Радарной станции."
   Modified 1715247194
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71BF01B871EA}" {
   Id "armst_quest_forest_search_ural_stage_2"
   Target_en_us "The bunker was destroyed, traces of a struggle and the remains of the expedition members were found inside. Notes were found on the walls of the bunker, which indicate that the scientific group headed to the local Caves for further research."
   Target_ru_ru "Бункер разрушен, внутри найдены следы борьбы и останки членов экспедиции. На стенах бункера найдены записи, в которых указано, что научная группа направилась в местные Пещеры для дальнейших исследований."
   Modified 1715247342
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71BF31800A4F}" {
   Id "armst_quest_forest_search_ural_stage_final"
   Target_en_us "It looks like the entire expedition perished in the Caves, at the hands of some creature. We need to get back to Petrov and report the situation."
   Target_ru_ru "Похоже, что вся экспедиция погибла в Пещерах, от рук какой-то твари. Нужно вернуться обратно к Петрову и доложить о ситуации."
   Modified 1715247504
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663C71B9144089DF}" {
   Id "armst_quest_forest_search_ural_start_mission"
   Target_en_us "We have a problem. Our expedition, which went to the Forest to study anomalies, has gone missing. We received a message that the helicopter that delivered them to their destination crashed in the forest. We suspect that the bunker that was supposed to be placed in the forest was dropped somewhere nearby."\
   ""\
   "We need you to check the helicopter and find out what happened to our expedition. We have received the coordinates of the crash site, they have been transmitted to you. Please be careful, the forest is full of dangers."\
   ""\
   "If you find something that can help us, please contact me. We will be very grateful to you"
   Target_ru_ru "У нас проблема. Наша экспедиция, отправившаяся в Лес для изучения аномалий, пропала без вести. Мы получили сообщение, что вертолет, доставивший их к месту назначения, потерпел крушение в лесу. Мы подозреваем, что бункер, который должен был быть размещен в лесу, был сброшен где-то поблизости."\
   ""\
   "Нам нужно, чтобы вы проверили вертолет и выяснили, что случилось с нашей экспедицией. Мы получили координаты места крушения, они переданы вам. Пожалуйста, будьте осторожны, лес полон опасностей."\
   ""\
   "Если вы найдете что-то, что может нам помочь, пожалуйста, свяжитесь со мной. Мы будем вам очень благодарны"
   Modified 1715373153
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663E738218895FE7}" {
   Id "armst_quest_kb_info"
   Target_en_us "We are Smugglers - a commercial organization engaged in trade and exchange of goods in the Zone. Our goal is to satisfy the demand for rare and valuable goods that can only be found in the Zone."\
   ""\
   "We work with various stalkers, scientists and other groups to gain access to rare artifacts, weapons and other valuable goods. We offer good pay to those who are ready to take a risk and get us what we need."\
   ""\
   "We do not interfere in politics and do not take sides in conflicts between other groups."\
   ""\
   "If you are ready to work with us and supply us with the goods we need, we are ready to pay you good money."
   Target_ru_ru "Мы Контрабандисты - коммерческая организация, занимающаяся торговлей и обменом товарами в Зоне. Наша цель - удовлетворять спрос на редкие и ценные товары, которые можно найти только в Зоне."\
   ""\
   "Мы работаем с различными сталкерами, учеными и другими группировками, чтобы получить доступ к редким артефактам, оружию и другим ценным товарам. Мы предлагаем хорошую оплату тем, кто готов рискнуть и добыть для нас то, что нам нужно."\
   ""\
   "Мы не вмешиваемся в политику и не принимаем стороны в конфликтах между другими группировками."\
   ""\
   "Если ты готов работать с нами и поставлять нам нужные товары, мы готовы платить тебе хорошие деньги."
   Modified 1715372731
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{6642BDCAA8C98BBB}" {
   Id "armst_quest_medic_info"
   Target_en_us "My name is Stepka. I got into an anomaly during one of the raids, and as you can see, I was pretty battered."\
   ""\
   "While I'm recovering, I made a deal with the Smugglers that I'll work part-time for them as a local medic, since I'm a former veterinarian, so I can do something."\
   ""\
   "If you need medical help, contact me!"
   Target_ru_ru "Меня Степка звать. В одном из рейдов попал в аномалию, вот, как видишь, сильно потрепало меня. "\
   ""\
   "Пока восстанавливаюсь, договорился с Контрабасами, что буду подрабатывать у них тут местным медиком, как никак я в прошлом ветеринар, что-то да умею."\
   ""\
   "Если тебе нужна медицинская помощь - обращайся! "
   Modified 1715652867
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A73912B3589}" {
   Id "armst_quest_savino_journalist_action_docs"
   Target_en_us "Inspect"
   Target_ru_ru "Осмотреть"
   Modified 1708950795
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A73C63D47E2}" {
   Id "armst_quest_savino_journalist_action_start"
   Target_en_us "1. The task is to establish Sviridov's fate"
   Target_ru_ru "1. Задание - установить судьбу Свиридова"
   Modified 1708950651
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A73E8379F8B}" {
   Id "armst_quest_savino_journalist_finish_mission"
   Target_en_us "You've managed to do it, and you clearly have the makings of a detective. I will give these personal documents to his relatives. I think when we collect more information about what is happening here, I will be able to write a big article that will cause a scandal in government circles. Someone has to answer for what happened."
   Target_ru_ru "Тебе удалось это сделать, в тебе явно есть хорошие задатки сыщика. Я передам эти личные документы его родственникам. Думаю, когда мы соберем больше материала о происходящем здесь, я смогу написать большую статью, которая вызовет скандал в правительственных кругах. Кто-то должен ответить за произошедшее."
   Modified 1708950742
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A70B0E226BB}" {
   Id "armst_quest_savino_journalist_item"
   Target_en_us "The Journalist's Notebook"
   Target_ru_ru "Блокнот Журналиста"
   Modified 1708951305
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A70A77CE02F}" {
   Id "armst_quest_savino_journalist_item_sviridov"
   Target_en_us "Sviridov's personal documents"
   Target_ru_ru "Личные документы Свиридова"
   Modified 1708951277
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A722E75CC7F}" {
   Id "armst_quest_savino_journalist_name"
   Target_en_us "Journalist"
   Target_ru_ru "Журналист"
   Modified 1708950615
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A7348009F6E}" {
   Id "armst_quest_savino_journalist_stage_1"
   Target_en_us "Among the many documents, you found a work record stating that he worked at a local farm."\
   "Considering that the body is not here, we need to check there, in case he was at work at the time of the disaster."
   Target_ru_ru "Среди множества документов, вы обнаружили трудовую книжку, в которой указано, что он работал на местном фермерском производстве."\
   "Учитывая, что тела здесь нет, нужно проверить там, вдруг он был на работе в момент катастрофы."
   Modified 1708950920
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A73209A2DF6}" {
   Id "armst_quest_savino_journalist_stage_2"
   Target_en_us "On the table, you found a log with a duty schedule, where you see a note that Sviridov was on shift on the day of the incident and was responsible for repairing cars. We need to find his workplace directly."
   Target_ru_ru "На столе вы обнаружили журнал с графиком дежурств, где видите отметку, что Свиридов был в смене в день инцидент и отвечал за ремонт машин. Нужно найти непосредственно его рабочее место. "
   Modified 1708951052
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A70D38B260E}" {
   Id "armst_quest_savino_journalist_stage_3"
   Target_en_us "This is an order from the military issued to Alexei Sviridov. The text states that he is obliged to immediately transport all injured farm staff, as well as the bodies of the dead, to the forestry department north of Savino. The document emphasizes that this is a temporary measure to provide first aid and isolate the incident area."
   Target_ru_ru "Это приказ от военных, выданный Алексею Свиридову. В тексте указано, что он обязан немедленно транспортировать всех пострадавших сотрудников фермы, а также тела погибших, к лесничеству на северо от Савино. В документе подчеркивается, что это временная мера для оказания первой помощи и изоляции зоны инцидента."
   Modified 1708951129
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A70F0C4BC35}" {
   Id "armst_quest_savino_journalist_stage_4"
   Target_en_us "After examining the body, you find a driver's license that belongs to Alexei Sviridov. Judging by the hole in his skull, he was shot at point-blank range with a pistol."
   Target_ru_ru "Осмотрев тело, вы находите водительское удостоверение, которое принадлежит Алексею Свиридову. Судя по отверстию в черепе, он был застрелен в упор из пистолета."
   Modified 1708951192
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A70EB5F0B0E}" {
   Id "armst_quest_savino_journalist_stage_4_action"
   Target_en_us "Take Sviridov's personal documents"
   Target_ru_ru "Взять личные документы Свиридова"
   Modified 1708951172
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A708E6C4D90}" {
   Id "armst_quest_savino_journalist_stage_4_finish"
   Target_en_us "Now you can return to the Journalist, I have established Sviridov's status. He was shot near the mass grave of farm workers."
   Target_ru_ru "Теперь можно вернуться к Журналисту, я установил статус Свиридова. Его расстреляли возле братской могилы рабочих с фермы."
   Modified 1708951241
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A73D468411A}" {
   Id "armst_quest_savino_journalist_start_mission"
   Target_en_us "My name is a Journalist, I am investigating the disaster in the Zone. As you know, the government is keeping quiet about the details of the tragedy, including the deaths of local residents. I was approached by the relatives of a certain Alexei Sviridov, who disappeared after the Disaster, with a request to find evidence of his death, apparently in order to inherit. "\
   "I know that he had a house in Savino. I need you to go through all the houses, maybe he's there. If there is no body, try to find some clues that will help us determine its status."
   Target_ru_ru "Меня звать Журналистом, я занимаюсь расследованием катастрофы в Зоне. Как ты знаешь, правительство замалчивает детали трагедии, в том числе и не сообщает о погибших местных жителях. Ко мне обратились родственники некоего Алексея Свиридова, который пропал после Катастрофы, с просьбой найти доказательства его смерти, видимо, чтобы вступить в наследство. "\
   "Мне известно, что у него был дом в Савино. Нужно чтобы ты прошерстил все дома, возможно он там. Если тела нет - попробуй найти какие-то зацепки, что помогут нам установить его статус. "
   Modified 1708950693
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A729F1652E5}" {
   Id "armst_quest_savino_tower_action"
   Target_en_us "Savino Radio Tower"
   Target_ru_ru "Радиовышка Савино"
   Modified 1708950357
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A72BD79DFCF}" {
   Id "armst_quest_savino_tower_finish_mission"
   Target_en_us "Great! Now we have up-to-date data on all radio waves within Savino. This will greatly help us in studying the anomalous phenomena in this area."
   Target_ru_ru "Отлично! Теперь мы имеем актуальные данные по всем радиоволнам в пределах Савино. Это очень поможет нам в изучении аномальных явлений в данной местности."
   Modified 1708950410
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A725E0F1424}" {
   Id "armst_quest_savino_tower_stage_1"
   Target_en_us "Insert a disk"
   Target_ru_ru "Вставить диск"
   Modified 1708950469
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A72694E541D}" {
   Id "armst_quest_savino_tower_stage_2"
   Target_en_us "Remove a disk"
   Target_ru_ru "Изъять диск"
   Modified 1708950487
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A7277D78496}" {
   Id "armst_quest_savino_tower_stage_3"
   Target_en_us "Uploading data... Completed."
   Target_ru_ru "Загрузка данных... Завершено."
   Modified 1708950506
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A7200D29066}" {
   Id "armst_quest_savino_tower_stage_4"
   Target_en_us "Removing the disk."
   Target_ru_ru "Извлечение диска."
   Modified 1708950539
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{65DC7A72AC87ED85}" {
   Id "armst_quest_savino_tower_start_mission"
   Target_en_us "Hello, stalker! I need you to take my floppy disk so that we can read the radio wave data in Savino County. We have already installed an uninterruptible power supply computer near the Radio Tower, you need to insert this disk into it, download all the data to it and bring it back."
   Target_ru_ru "Привет, сталкер! Мне нужно, чтобы ты взял мой флоппи-диск, чтобы мы могли считать данные радиоволн в округе Савино. Мы уже установили возле Радиовышки компьютер с бесперебойным питанием, тебе необходимо вставить в него этот диск, загрузить на него все данные и принести обратно."
   Modified 1708950383
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663E738D8F8859AE}" {
   Id "armst_quest_science_ural_info"
   Target_en_us "My name is Doctor Malakhitov, I am from the scientific group 'Prometheus'. We are a group of scientists studying anomalies and phenomena in the Zone. Our goal is to understand the nature of the Zone and how to interact with it."\
   ""\
   "We conduct research in various fields to better understand what is happening in the Zone. We pay special attention to the development of scientific equipment that could help stalkers and other people working in the Zone feel safer."\
   ""\
   "We are engaged in the development and production of anomaly detectors, dosimeters, protective gear and other equipment that is necessary for working in the Zone. Our developments help stalkers detect and avoid dangers, as well as more effectively explore the Zone."
   Target_ru_ru "Меня зовут доктор Малахитов, я из научной группы 'Прометей'. Мы - группа ученых, занимающихся изучением аномалий и явлений в Зоне. Наша цель - понять природу Зоны и как с ней взаимодействовать."\
   ""\
   "Мы проводим исследования в различных областях, чтобы лучше понять, что происходит в Зоне. Особое внимание мы уделяем разработке научного оборудования, которое могло бы помочь сталкерам и другим людям, работающим в Зоне, чувствовать себя более безопасно."\
   ""\
   "Мы занимаемся разработкой и производством детекторов аномалий, дозиметров, защитного снаряжения и другого оборудования, которое необходимо для работы в Зоне. Наши разработки помогают сталкерам обнаруживать и избегать опасностей, а также более эффективно исследовать Зону."
   Modified 1715373899
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{663E7383181645A4}" {
   Id "armst_quest_storm_info"
   Target_en_us "My name is Commander Orlov, I represent the Storm group. We are a military organization created to protect people from threats coming from the Zone. Our mission is to clear the Zone of mutants and anomalies, and to protect the Perimeter from the penetration of hostile elements."\
   ""\
   "We are a disciplined and well-trained group, our goal is to make the Zone safer for everyone. We do not pursue personal interests, our goal is to serve the common good."\
   ""\
   "Unfortunately, after the recent war, we lost a lot of good fighters and there are very few of us left."
   Target_ru_ru "Меня зовут командир Орлов, я представляю группировку 'Шторм'. Мы - военная организация, созданная для защиты людей от угроз, исходящих из Зоны. Наша миссия - очищать Зону от мутантов и аномалий, а также защищать Периметр от проникновения враждебных элементов."\
   ""\
   "Мы - дисциплинированная и хорошо обученная группировка, наша цель - сделать Зону более безопасной для всех. Мы не преследуем личных интересов, наша цель - служение общему благу."\
   ""\
   "К сожалению, после недавней войны, мы потеряли очень много хороших бойцов и нас осталось очень мало."
   Modified 1715372344
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{662CA2DA46EF0745}" {
   Id "armst_quest_swamp_action_antena"
   Target_en_us "Collect data"
   Target_ru_ru "Собрать данные"
   Modified 1714202472
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{662CA2DA528A2665}" {
   Id "armst_quest_swamp_action_antena_final"
   Target_en_us "Scanning complete"
   Target_ru_ru "Сканирование завершено"
   Modified 1714202490
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{662CA2D97709C5C6}" {
   Id "armst_quest_swamp_finish_mission"
   Target_en_us "You're taking a long time, are there any problems with the equipment? Give me the analyzer... No, everything is fine, all the data is recorded correctly. Thank you for helping science!"
   Target_ru_ru "Что-то ты долго, возникли какие-то проблемы с оборудованием? Давай сюда анализатор... Нет, всё в порядке, все данные записаны корректно. Спасибо за содействие науке!"
   Modified 1714202145
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{662CA2D93062274E}" {
   Id "armst_quest_swamp_search_action"
   Target_en_us "Exploring the Swamps"
   Target_ru_ru "Исследование Болот"
   Modified 1714202212
   Author "romzet"
   LastChanged "romzet"
  }
  CustomStringTableItem "{662CA2D9ACA0B3F8}" {
   Id "armst_quest_swamp_start_mission"
   Target_en_us "Hello!"\
   "Now you can finally get to the local Swamps. I am not allowed there yet, but you can take the necessary measurements for me."\
   ""\
   "I have marked the points on the map where you need to take measurements, I will give you the necessary device."\
   ""\
   "When you have taken all the data from all the points, come back. In total, you need to find 4 antennas and take measurements there."
   Target_ru_ru "Привет!"\
   "Теперь ты наконец-то можешь добраться до местных Болот. Меня туда пока не допускают, однако ты можешь сделать необходимые замеры за меня. "\
   "Я обозначил тебе на карте точки, где необходимо снять замеры, нужный прибор я тебе выдам. "\
   "Когда снимешь все данные со всех точек - возвращайся. Всего тебе нужно найти 4 антенны и провести там замеры."
   Modified 1714202861
   Author "romzet"
   LastChanged "romzet"
  }
 }
}