
modded class SCR_SoundEvent
{
	static const string ARMST_LOOT_SOUND_BOX = "ARMST_LOOT_SOUND_BOX";
	static const string ARMST_LOOT_SOUND_INV = "ARMST_LOOT_SOUND_INV";
	static const string DETECTOR_GEIGER_ACTIVE = "DETECTOR_GEIGER_ACTIVE";
	static const string PSY_SOUND = "PSY_SOUND";
	static const string DETECTOR_ART_LEVEL_SELECT_BUTTON = "DETECTOR_ART_LEVEL_SELECT_BUTTON";
	static const string DETECTOR_ART_LEVEL_ANALIS_FOUND = "DETECTOR_ART_LEVEL_ANALIS_FOUND";
	static const string DETECTOR_ART_LEVEL_ANALIS_FOUNDED = "DETECTOR_ART_LEVEL_ANALIS_FOUNDED";
	static const string DETECTOR_ART_LEVEL_ANALIS_NOT_FOUNDED = "DETECTOR_ART_LEVEL_ANALIS_NOT_FOUNDED";
	
	static const string ARMST_ITEM_USED = "ARMST_ITEM_USED";
}